[tools]
java = "temurin-21.0.2+13.0.LTS"
clojure = "1.12.0.1479"
babashka = "1.12.194"
clj-kondo = "2024.09.27"
cljfmt = "0.13.0"
lefthook = "1.11.2"

[alias]
cljfmt = "asdf:https://github.com/b-social/asdf-cljfmt"
