name: Deploy Snapshot

on:
  push:
    branches: [ master ]

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
#          cache: 'maven'
      - uses: jdx/mise-action@v2
        with:
#          install_args: "babashka java clojure"
          install_args: "babashka clojure"
      - name: Deploy Snapshot
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: bb deploy-snapshot
